[package]
name = "metronorust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#plotlib = "0.5.1"
cpal = "0.13.5"
clap = "3.1.12"
#anyhow = "1.0.57"